-- Faixas etárias (o "trilho" de categorias da loja). O slug aparece na URL
-- pública (/jogos?idade=4-6), por isso fica em português.
CREATE TABLE categories (
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slug     VARCHAR(60)  NOT NULL UNIQUE,
    name     VARCHAR(100) NOT NULL,
    position INT          NOT NULL DEFAULT 0
);

CREATE TABLE products (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slug           VARCHAR(120)   NOT NULL UNIQUE,
    name           VARCHAR(150)   NOT NULL,
    icon           VARCHAR(16),
    description    VARCHAR(4000)  NOT NULL,
    skill          VARCHAR(100)   NOT NULL,
    category_id    BIGINT         NOT NULL REFERENCES categories (id),
    age_label      VARCHAR(40)    NOT NULL,
    players        VARCHAR(60)    NOT NULL,
    price          NUMERIC(10, 2) NOT NULL CHECK (price > 0),
    -- Preenchido = produto em promoção (price passa a ser o preço promocional).
    original_price NUMERIC(10, 2) CHECK (original_price IS NULL OR original_price > price),
    stock          INT            NOT NULL DEFAULT 0 CHECK (stock >= 0),
    cooperative    BOOLEAN        NOT NULL DEFAULT FALSE,
    -- Até quando o produto aparece em Novidades (NULL = não é novidade).
    new_until      TIMESTAMP WITH TIME ZONE,
    created_at     TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at     TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_products_category ON products (category_id);

-- Avaliações de clientes: só aparecem na loja depois de aprovadas pelo admin.
CREATE TABLE reviews (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id  BIGINT        NOT NULL REFERENCES products (id) ON DELETE CASCADE,
    author_name VARCHAR(80)   NOT NULL,
    rating      INT           NOT NULL CHECK (rating BETWEEN 1 AND 5),
    comment     VARCHAR(1000) NOT NULL,
    status      VARCHAR(20)   NOT NULL DEFAULT 'PENDING'
                CHECK (status IN ('PENDING', 'APPROVED', 'REJECTED')),
    created_at  TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_reviews_product_status ON reviews (product_id, status);
