-- E-mails com acesso ao painel admin (login com Google). Gerenciado pelo
-- próprio painel em /admin/admins. O primeiro admin é criado na subida da
-- aplicação a partir de ADMIN_BOOTSTRAP_EMAIL (ver AdminBootstrap).
CREATE TABLE admin_users (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email            VARCHAR(254) NOT NULL UNIQUE,
    created_by_email VARCHAR(254),
    created_at       TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);
