-- Conteúdo da página /sobre, editável pelo painel (/admin/sobre).
-- Uma única linha em about_page; os cards de valores ficam em about_values.
CREATE TABLE about_page (
    id               BIGINT PRIMARY KEY CHECK (id = 1),
    hero_text        VARCHAR(4000) NOT NULL,
    mission_emoji    VARCHAR(16),
    mission_title    VARCHAR(200)  NOT NULL,
    mission_text     VARCHAR(4000) NOT NULL,
    updated_by_email VARCHAR(254),
    updated_at       TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE about_values (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    about_page_id BIGINT       NOT NULL REFERENCES about_page (id) ON DELETE CASCADE,
    position      INT          NOT NULL,
    icon          VARCHAR(16),
    title         VARCHAR(100) NOT NULL,
    text          VARCHAR(1000) NOT NULL
);

-- Texto provisório (o mesmo do frontend) até a Donna enviar o conteúdo real.
INSERT INTO about_page (id, hero_text, mission_emoji, mission_title, mission_text) VALUES (1,
    'O nome ASOBI vem do japonês 遊び ("asobi"), que significa brincadeira. Acreditamos que é brincando que as crianças aprendem melhor — e é por isso que existimos: para levar até as famílias jogos de tabuleiro que unem diversão de verdade com desenvolvimento infantil.',
    '🎲',
    'Ajudar cada família a escolher o jogo certo',
    'Em cada produto do nosso catálogo, mostramos a idade recomendada, o número de jogadores e a habilidade que aquele jogo estimula — raciocínio lógico, trabalho em equipe, coordenação motora, criatividade e muito mais. Assim, escolher o presente certo fica mais simples e divertido.');

INSERT INTO about_values (about_page_id, position, icon, title, text) VALUES
    (1, 1, '🎲', 'Aprender brincando', 'Selecionamos jogos que unem diversão de verdade com estímulo ao desenvolvimento infantil.'),
    (1, 2, '🔎', 'Curadoria cuidadosa', 'Cada jogo do catálogo é escolhido a dedo, com idade recomendada e habilidade estimulada bem claras.'),
    (1, 3, '👨‍👩‍👧', 'Feito para famílias', 'Queremos facilitar a vida de quem está escolhendo o presente certo para uma criança.'),
    (1, 4, '🛡️', 'Segurança em primeiro lugar', 'Cuidamos dos dados dos responsáveis com atenção especial por atender o público infantil.');
