-- Pedidos. Checkout sem cadastro: guarda só os dados do adulto que compra
-- (LGPD — nenhum dado da criança). Itens guardam nome e preço do momento da
-- compra, para o histórico não mudar se o produto for editado ou excluído.
CREATE TABLE orders (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id            UUID          NOT NULL UNIQUE,
    status               VARCHAR(20)   NOT NULL
                         CHECK (status IN ('PENDING_PAYMENT', 'PAID', 'SHIPPED', 'CANCELED')),
    customer_name        VARCHAR(120)  NOT NULL,
    customer_email       VARCHAR(254)  NOT NULL,
    customer_phone       VARCHAR(30)   NOT NULL,
    shipping_postal_code VARCHAR(9)    NOT NULL,
    shipping_street      VARCHAR(200)  NOT NULL,
    shipping_number      VARCHAR(20)   NOT NULL,
    shipping_complement  VARCHAR(100),
    shipping_district    VARCHAR(100)  NOT NULL,
    shipping_city        VARCHAR(100)  NOT NULL,
    shipping_state       VARCHAR(2)    NOT NULL,
    items_total          NUMERIC(10, 2) NOT NULL,
    shipping_cost        NUMERIC(10, 2) NOT NULL DEFAULT 0,
    total                NUMERIC(10, 2) NOT NULL,
    payment_provider     VARCHAR(30),
    payment_id           VARCHAR(64),
    payment_status       VARCHAR(40),
    payment_method       VARCHAR(40),
    -- Pago, mas o estoque acabou antes (duas compras do último item ao mesmo tempo).
    stock_issue          BOOLEAN       NOT NULL DEFAULT FALSE,
    tracking_code        VARCHAR(60),
    paid_at              TIMESTAMP WITH TIME ZONE,
    shipped_at           TIMESTAMP WITH TIME ZONE,
    created_at           TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at           TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_orders_status_created ON orders (status, created_at);

CREATE TABLE order_items (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id     BIGINT         NOT NULL REFERENCES orders (id) ON DELETE CASCADE,
    product_id   BIGINT         REFERENCES products (id) ON DELETE SET NULL,
    product_slug VARCHAR(120)   NOT NULL,
    product_name VARCHAR(150)   NOT NULL,
    unit_price   NUMERIC(10, 2) NOT NULL,
    quantity     INT            NOT NULL CHECK (quantity > 0),
    line_total   NUMERIC(10, 2) NOT NULL
);

CREATE INDEX idx_order_items_order ON order_items (order_id);
