-- Fotos dos produtos. O arquivo fica no storage (Supabase Storage em produção);
-- aqui guardamos só a chave dele. A foto de menor "position" é a capa.
CREATE TABLE product_images (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id  BIGINT       NOT NULL REFERENCES products (id) ON DELETE CASCADE,
    storage_key VARCHAR(200) NOT NULL UNIQUE,
    position    INT          NOT NULL DEFAULT 0,
    created_at  TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_product_images_product ON product_images (product_id, position);
